# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See LICENSE file in the project root for license information.
#
# Simplified PowerShell script to deploy ONLY the Customer Portal
# Skips database migration - use this for code-only updates
#

Param(  
   [string][Parameter(Mandatory)]$WebAppNamePrefix, # Prefix used for creating web applications
   [string][Parameter(Mandatory)]$ResourceGroupForDeployment # Name of the resource group to deploy the resources
)

# Define the message
$message = @"
The SaaS Accelerator is offered under the MIT License as open source software and is not supported by Microsoft.

If you need help with the accelerator or would like to report defects or feature requests use the Issues feature on the GitHub repository at https://aka.ms/SaaSAccelerator

This simplified script deploys ONLY the Customer Portal (no database migration).

Do you agree? (Y/N)
"@

# Display the message in yellow
Write-Host $message -ForegroundColor Yellow

# Prompt the user for input
$response = Read-Host

# Check the user's response
if ($response -ne 'Y' -and $response -ne 'y') {
    Write-Host "You did not agree. Exiting..." -ForegroundColor Red
    exit
}

# Proceed if the user agrees
Write-Host "Thank you for agreeing. Proceeding with the Customer Portal deployment..." -ForegroundColor Green
Write-Host ""

#Get TenantID if not set as argument
$currentContext = az account show | ConvertFrom-Json
$currentTenant = $currentContext.tenantId
$currentSubscription = $currentContext.id

Get-AzTenant | Format-Table
$TenantID = $null
if (!($TenantID = Read-Host "⌨  Type your TenantID or press Enter to accept your current one [$currentTenant]")) { $TenantID = $currentTenant }  

#Get Azure Subscription if not set as argument
Get-AzSubscription -TenantId $TenantID | Format-Table
$AzureSubscriptionID = $null
if (!($AzureSubscriptionID = Read-Host "⌨  Type your SubscriptionID or press Enter to accept your current one [$currentSubscription]")) { $AzureSubscriptionID = $currentSubscription }

Write-Host "🔑 Azure Subscription '$AzureSubscriptionID' selected." -ForegroundColor Cyan

# Set Azure subscription
Set-AzContext -Subscription $AzureSubscriptionID -Tenant $TenantID | Out-Null

# ============================================================================
# Configuration
# ============================================================================
$WebAppNamePortal = "$WebAppNamePrefix-portal"

Write-Host ""
Write-Host "=========================================="  -ForegroundColor Cyan
Write-Host "Customer Portal Deployment Configuration" -ForegroundColor Cyan
Write-Host "=========================================="  -ForegroundColor Cyan
Write-Host "  Resource Group: $ResourceGroupForDeployment" -ForegroundColor White
Write-Host "  Customer Portal: $WebAppNamePortal" -ForegroundColor White
Write-Host ""

# ============================================================================
# Deploy Customer Portal Code
# ============================================================================
Write-Host "#### Deploying Customer Portal ####" -ForegroundColor Green
Write-Host ""

Write-Host "## STEP 1: Git pull latest changes" -ForegroundColor Yellow
Set-Location ..
git pull origin main
Write-Host "✅ Code updated" -ForegroundColor Green
Write-Host ""

Write-Host "## STEP 2: Clean old publish directory" -ForegroundColor Yellow
if (Test-Path "./Publish") {
    Remove-Item -Path "./Publish" -Recurse -Force
}
New-Item -Path "./Publish" -ItemType Directory -Force | Out-Null
Write-Host "✅ Publish directory cleaned" -ForegroundColor Green
Write-Host ""

Write-Host "## STEP 3: Building Customer Portal" -ForegroundColor Yellow
dotnet publish ./src/CustomerSite/CustomerSite.csproj -v q -c release -o ./Publish/CustomerSite
if ($LASTEXITCODE -ne 0) {
    Write-Host "❌ ERROR: CustomerSite build failed" -ForegroundColor Red
    exit 1
}
Write-Host "✅ CustomerSite built successfully" -ForegroundColor Green
Write-Host ""

Write-Host "## STEP 4: Compress package" -ForegroundColor Yellow
Compress-Archive -Path ./Publish/CustomerSite/* -DestinationPath ./Publish/CustomerSite.zip -Force
$zipSize = (Get-Item "./Publish/CustomerSite.zip").Length / 1MB
Write-Host "✅ Package created: $([math]::Round($zipSize, 2)) MB" -ForegroundColor Green
Write-Host ""

Write-Host "## STEP 5: Verify web.config was auto-generated" -ForegroundColor Yellow
if (Test-Path "./Publish/CustomerSite/web.config") {
    Write-Host "✅ web.config found in publish output (auto-generated by dotnet publish)" -ForegroundColor Green
    Write-Host ""
    Write-Host "   Content preview:" -ForegroundColor Gray
    Get-Content "./Publish/CustomerSite/web.config" | Select-Object -First 10 | ForEach-Object { Write-Host "   $_" -ForegroundColor Gray }
    Write-Host ""
} else {
    Write-Host "⚠️  WARNING: web.config not found in publish output" -ForegroundColor Yellow
    Write-Host ""
}

Write-Host "## STEP 6: Deploying to Azure App Service" -ForegroundColor Yellow
Write-Host "   Resource Group: $ResourceGroupForDeployment" -ForegroundColor White
Write-Host "   App Service: $WebAppNamePortal" -ForegroundColor White
Write-Host "   Method: az webapp deploy --type zip (modern deployment)" -ForegroundColor White
Write-Host ""

az webapp deploy `
    --resource-group $ResourceGroupForDeployment `
    --name $WebAppNamePortal `
    --src-path "./Publish/CustomerSite.zip" `
    --type zip

if ($LASTEXITCODE -ne 0) {
    Write-Host "❌ ERROR: Deployment failed" -ForegroundColor Red
    exit 1
}
Write-Host "✅ Code deployment completed" -ForegroundColor Green
Write-Host ""

# ============================================================================
# Cleanup
# ============================================================================
Write-Host "## STEP 7: Cleanup" -ForegroundColor Yellow
# Keep Publish directory for debugging
# Remove-Item -Path ./Publish -Recurse -Force
Write-Host "✅ Deployment complete (Publish directory kept for debugging)" -ForegroundColor Green
Write-Host ""

# ============================================================================
# Summary
# ============================================================================
Write-Host "==========================================" -ForegroundColor Green
Write-Host "✅ Customer Portal Deployment Completed!" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "1. Wait 30 seconds for application restart" -ForegroundColor White
Write-Host "2. Test portal: https://$WebAppNamePortal.azurewebsites.net" -ForegroundColor White
Write-Host "3. If issues, check logs:" -ForegroundColor White
Write-Host "   az webapp log tail --resource-group $ResourceGroupForDeployment --name $WebAppNamePortal" -ForegroundColor Gray
Write-Host "4. Verify HTTP status:" -ForegroundColor White
Write-Host "   curl -I https://$WebAppNamePortal.azurewebsites.net" -ForegroundColor Gray
Write-Host ""
Write-Host "Published files location: ./Publish/CustomerSite/" -ForegroundColor Yellow
Write-Host ""
